# This section defines all your connection details using a token.
# At least the domain is required. Username and API token can also be entered when executing the script.
Connection:
    Domain: https://example.atlassian.net
    Username: example@address.com
    API Token: MYEXAMPLETOKENFROMATLASSIANID
    Cloud: !!bool Yes

# This section defines what you are searching for.
# You must at least define one project key or a filter. If the project key is defined, the filter will be ignored.
Search Criteria:
    # The following filter that is defined inside Jira will be applied.
    # Make sure that the user you are logging in with this script can access the filter.
    # Uncomment if you want to use this YAML file to define your filter by
    # defining project keys, issue types, and dates.
    Filter: My Example Filter
    # Specify a list of projects instead of using a filter.
    # Obsolete if a filter is defined.
    Projects:
        - PROJECT
    # Restrict the search result to the given issue types.
    # Obsolete if a filter is defined.
    Issue Types:
        - Story
        - Task
        - Bug
    # Exclude issues created before the following date, YYYY-MM-DD
    # Obsolete if a filter is defined.
    Exclude Created Date: 2022-01-01
    # Exclude issues resolved before the following date, YYYY-MM-DD
    # Obsolete if a filter is defined.
    Exclude Resolved Date: 2023-01-01

# Mandatory attributes to define
Mandatory:
    Parent Link Field ID: customfield_10018 # Make sure that this is the correct id for the custom field 'Parent Link'
    Flagged Field ID: customfield_10021 # Make sure that this is the correct id for the custom field 'Flagged'

# Define which standard fields should the export contain
Standard Issue Fields:
    Type: !!bool Yes
    Summary: !!bool Yes
    Reporter: !!bool Yes
    Assignee: !!bool Yes
    Status: !!bool Yes
    Resolution: !!bool Yes
    Priority: !!bool Yes
    Flagged: !!bool Yes
    Created: !!bool Yes
    Updated: !!bool Yes
    Resolved: !!bool Yes
    Due Date: !!bool Yes
    Parent: !!bool Yes
    Labels: !!bool Yes
    Components: !!bool Yes
    Fixed Versions: !!bool Yes
    Affected Versions: !!bool Yes

# Define which custom fields the export should contail by mapping field names to custom field IDs
# Make sure that the IDs are correct. You can check this by exporting a single issue to CSV
# and checking the header line of the resulting file.
Custom Issue Fields:
    story-point-estimate: customfield_10016

# Describe the workflow. Each step can be mapped to either a single JIRA
# status, or a list of statuses that will be treated as equivalent
Workflow:
    backlog: # A category for the given status
        - To Do # A status as defined inside Jira
        - Open
    in-progress:
        - In Progress
    done:
        - Done
        - Closed

# Additional settings that are optional
Misc:
    CSV Separator: Comma # Choose between 'Comma' and 'Semicolon', default is Comma
    Standard Field Prefix: "std::" # Recommended to avoid confusion with other fields
    Custom Field Prefix: "cst::" # Recommended to avoid confusion with other fields
    # Choose whether to export the IDs of fields values in addition to their values. Default is No.
    # This can be useful for, e.g. select list fields like Priority or Resolution, where the value might change but the ID remains the same.
    # The IDs will be exported in additional columns with the postfix defined below.
    # Note: This applies to standard fields custom fields, as far as a value id is available.
    Export Value IDs: !!bool No 
    Issue Field ID Postfix: "::id" # Postfix to append to field IDs when exporting them, e.g. "std::Priority::id"
    Status Category Prefix: "cat::" # Recommended to avoid confusion whith other fields
    Time Zone: Europe/Berlin # Set a time zone accoring to pytz.all_timezones, e.g. Europe/Berlin, US/Pacific, Asia/Tokyo. Default is UTC.
    Date Format: "%Y-%m-%d" # Choose a date format according to Python's datetime formatting options. Default is "%Y-%m-%d".
    DateTime Option: Date # Choose between 'Date', 'Seconds' and 'Milliseconds', default is 'Date'.
    DateTime Format: "%Y-%m-%d %H:%M:%S" # Choose a datetime format according to Python's datetime formatting options. Default is "%Y-%m-%d %H:%M:%S".
    Decimal Separator: Comma # Choose between 'Comma' and 'Point', default is 'Point'
