# This section defines all your connection details using a token.
# At least the domain is required. Username and API token can also be entered when executing the script.
Connection:
    Domain: https://example.atlassian.net
    Username: example@address.com
    #API Token: 

# This section defines what you are searching for.
# You must at least define one project key or a filter. If the project key is defined, the filter will be ignored.
Search Criteria:
    # Specify a list of projects instead of using a filter.
    # The filter will be ignored if this is activated (not commented out).
    #Projects:
    #    - PROJECT
    # Restrict the search result to the given issue types.
    # This might be useful when not using a dedicated filter.
    #Issue Types:
    #    - Story
    #    - Task
    #    - Bug
    # The following filter will be applied.
    Filter: My Example Filter
    # Exclude issues created before the following date, YYYY-MM-DD
    Exclude Created Date: 2022-01-01
    # Exclude issues resolved before the following date, YYYY-MM-DD
    Exclude Resolved Date: 2023-01-01
    # Define the maximum amount of returned search results
    Max Results: 200

# Define which default fields should the export contain
Default Issue Fields:
    Reporter: !!bool Yes
    Assignee: !!bool Yes
    Summary: !!bool Yes
    Status: !!bool Yes
    Resolution: !!bool Yes
    Priority: !!bool Yes
    Created: !!bool Yes
    Resolved: !!bool Yes
    Flagged: !!bool Yes
    Labels: !!bool Yes

# Map field names to additional attributes to extract
Custom Issue Fields:
    story-points: customfield_10028

# Describe the workflow. Each step can be mapped to either a single JIRA
# status, or a list of statuses that will be treated as equivalent
Workflow:
    backlog: # A category for the given status
        - To Do # A status as defined inside Jira
        - Open
    in-progress:
        - In Progress
    done:
        - Done
        - Closed

# Mandatory properties to define
Additional Mandatory:
    Flagged Field ID: customfield_10021 # Make sure that this is the correct id for the custom field 'Flagged'

# Additional settings that are optional
Misc:
    Status Category Prefix: "category::" # Recommended to avoid confusion whith other fields
    Custom Field Prefix: "field::" # Recommended to avoid confusion with other fields
    Decimal Separator: Comma # Choose between 'Comma' and 'Point'
    Time Zone: Europe/Berlin # Not used yet 
